name: Publish Docker image
on:
  workflow_dispatch:
  
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository:  devofcode123/sigidoc_latest/sigidoc
          tag_with_ref: true
          dockerfile: SigiDoc_EFES_LATEST_in progress/EFES-master/Dockerfile
  deploy:
    name: Deploy image
    runs-on: self-hosted
    steps:
      - name: Pull image
        run: docker pull docker.pkg.github.com/devofcode123/sigidoc_latest/sigidoc:latest
      - name: Run image
        run: docker run -it -p 9000:9999 --rm --name sigidoc docker.pkg.github.com/devofcode123/sigidoc_latest/sigidoc:latest
